# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

# custom format
format = """
[╭─ $shell────$custom_brew────────$memory_usage──╌╌ $git_branch$git_metrics$git_commit$aws$buf$bun$c$cmake$conda$crystal$dart$deno$docker_context$elixir$elm$fennel$fortran$fossil_branch$gcloud$golang$gradle$guix_shell$haskell$haxe$hg_branch$java$julia$kotlin$lua$meson$nim$nix_shell$nodejs$ocaml$package$perl$php$pijul_channel$pixi$python$rlang$ruby$rust$scala$swift$xmake$zig$cmd_duration](overlay0)
[├─](overlay0)$sudo$username$hostname $directory$read_only
[╰─ $os$character](overlay0)"""

#format = '$all$directory$character'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 100
command_timeout = 500
add_newline = true

# Catppuchin Theme

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[shell]
fish_indicator = '🐟'
bash_indicator = 'bash'
unknown_indicator = 'unknown'
style = 'text'
disabled = false

[sudo]
symbol = '🧙'
format = ' $symbol'
disabled = false

[username]
style_user = 'lavender'
format = ' [$user]($style)'
disabled = false
show_always = true


[hostname]
ssh_only = true
ssh_symbol = " "
format = '[$ssh_symbol](pink)[$hostname](sapphire)'
trim_at = ''
disabled = false

[os]
disabled = false
format = "[$symbol]($style) "
style = "text"

[memory_usage]
symbol = "󰍛"
disabled = false
threshold = 50
format = ' [$symbol $ram_pct]($style) '
style = 'peach'

[custom.brew]
command = "fish -c 'brew_outdated_count 3600'"
when = "command -v brew >/dev/null 2>&1"
shell = ["sh", "-c"]  # laisse Starship lancer fish via sh -c
format = "[$symbol$output]($style) "
symbol = "🍺 "
style = "peach"

[localip]
ssh_only = false
format = '[@$localipv4](blue) '
disabled = false

[git_metrics]
disabled = false
format = ' [+$added](green) [-$deleted](red) '

[git_branch]
symbol = ""
format = '[$symbol $branch(:$remote_branch)]($style)'
style = 'pink'

[git_commit]
disabled = false
tag_symbol = '  '

[cmd_duration]
min_time = 500
format = ' took [$duration](rosewater)'

[directory]
fish_style_pwd_dir_length = 7
disabled = false
truncation_length = 4
truncation_symbol = '…/'
read_only = " 󰌾"
read_only_style = 'dimmed blue'
style = 'blue'

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](subtext1)" # For use with zsh-vi-mode

# battery
[battery]
full_symbol = '● '
charging_symbol = '◉ '
discharging_symbol = '◯ '

[[battery.display]]
threshold = 20
style = 'red'

[[battery.display]]
threshold = 100
style = 'teal'



[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

